# Generated by Django 2.2.9 on 2020-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200417_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Подробно опишите Вашу группу тут', verbose_name='Описание группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='https://myblog.com/groops/"cсылка на Вашу группу" (не более 200 символов)', max_length=200, unique=True, verbose_name='Cсылка'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Название группы (не более 200 символов)', max_length=200, verbose_name='Название группы'),
        ),
    ]
