# Generated by Django 2.2.9 on 2020-05-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200418_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='https://myblog.com/groups/"cсылка на Вашу группу" (не более 200 символов)', max_length=200, unique=True, verbose_name='Cсылка'),
        ),
    ]
