# Generated by Django 2.2.9 on 2020-05-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200512_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Опишите Вашу группу тут', verbose_name='Описание группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='https://myblog.com/groups/ "cсылка на Вашу группу" (не более 200 символов)', max_length=200, unique=True, verbose_name='Cсылка'),
        ),
    ]
